// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2PreRv_QuQBFDO9Zdw3E6Y459j20POoM',
    appId: '1:63390293824:web:b0140b1636777957a264a5',
    messagingSenderId: '63390293824',
    projectId: 'healthapp-76324',
    authDomain: 'healthapp-76324.firebaseapp.com',
    storageBucket: 'healthapp-76324.appspot.com',
    measurementId: 'G-F12D8FHLZ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXpeKq-RS-vUXAo45mMydr3nXJYaHAJ4k',
    appId: '1:63390293824:android:4469d91deae162aca264a5',
    messagingSenderId: '63390293824',
    projectId: 'healthapp-76324',
    storageBucket: 'healthapp-76324.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYb4fxApiNvmTpa7HrIWsV8Lodgfi9kKk',
    appId: '1:63390293824:ios:f54415f9eb9e704aa264a5',
    messagingSenderId: '63390293824',
    projectId: 'healthapp-76324',
    storageBucket: 'healthapp-76324.appspot.com',
    iosClientId: '63390293824-n6icns39osdqmcea4lh5u4mc394l6cue.apps.googleusercontent.com',
    iosBundleId: 'com.example.health',
  );
}
